// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {model} from '../models';

export function Close():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetFilesMetadata():Promise<Array<model.FileRecord>>;

export function Minimize():Promise<void>;

export function OffloadFile(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function ToggleFullscreen():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UploadFile(arg1:string):Promise<string>;
