// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
